### ISSUE TITLE
local time keep the same format as utc

### ISSUE THREAD

**Issue by dobefore** [rnag/sensible-env-logger#5]
### Description

I am so excited that the crate support local time,thank you for the wonderful job.
Can you format the loca time with the same format as utc,at least add date prefix?

**Comment by rnag** [comment]
I think it's a good idea! I would propose adding maybe a `bool` argument to the macro call `init_timed_short`, or maybe just creating a separate macro like `init_timed_local!()`.  I think the second option would probably be the easiest to work with.

A PR for adding this feature would be very welcome, otherwise I will look into adding this feature when I have some free time, as it should be a relatively easy change, I guess maybe 1-2 hours max of work involved, overall.

**Comment by rnag** [comment]
@dobefore done! I've added two helper macros with two different formats of local date/time, depending on the use case or whichever works best. These updates should be added as of version `0.3.0`.

- [`init_timed_local`](https://docs.rs/sensible-env-logger/latest/sensible_env_logger/macro.init_timed_local.html)
- [`init_timed_local_iso`](https://docs.rs/sensible-env-logger/latest/sensible_env_logger/macro.init_timed_local_iso.html)

**Comment by dobefore** [comment]
@rnag ,thanks,I'll try this.
